---
- name: Deploy Infra Components for DevOps with OpenShift and OpenShift Ansible Broker Workshop
  hosts: localhost
  gather_facts: false
  run_once: true
  vars:
    infra_project: lab-infra
    user_gogs_name: developer
    user_gogs_password: openshift
    user_gogs_admin: gogs
    user_gogs_admin_password: openshift
    generated_gogs_user_count: 0
    generated_gogs_user_format: user%02d
    generate_gogs_users: false
    labs_github_ref: master
  
  tasks:
    - include_role:
        name: openshift_common_facts
      tags: always

    - import_role:
        name: openshift_sonatype_nexus
      vars:
        project_name: "{{ infra_project }}"
        nexus_image_version: 3.7.1
      tags: nexus

    - import_role:
        name: openshift_workshopper
      vars:
        project_name: "{{ infra_project }}"
        workshopper_content_url_prefix: "https://raw.githubusercontent.com/openshift-labs/devops-oab-guides/master"
        workshopper_workshop_urls: "https://raw.githubusercontent.com/openshift-labs/devops-oab-guides/master/_devops-workshop.yml"
        workshopper_env_vars:
          PROJECT_SUFFIX: ""
          GOGS_URL: http://{{ gogs_hostname }}
          OPENSHIFT_DOCS_BASE: "https://docs.openshift.com/container-platform/3.7"
      tags: guides

    - set_fact:
        gogs_hostname: gogs-{{ infra_project }}.{{ apps_hostname_suffix }}
      tags: gogs

    - import_role:
        name: openshift_gogs
      vars:
        project_name: "{{ infra_project }}"
        project_display_name: "DevOps Workshop Infrastructure"
        project_desc: "DevOps Workshop Infrastructure"
        gogs_route: "{{ gogs_hostname }}"
        gogs_image_version: 0.11.34
        gogs_admin_user: "{{ user_gogs_admin }}"
        gogs_user: "{{ user_gogs_name }}"
        gogs_admin_password: "{{ user_gogs_password }}"
        gogs_password: "{{ user_gogs_admin_password }}"
        gogs_generate_user_count: "{{ generated_gogs_user_count }}"
        gogs_generate_user_format: "{{ generated_gogs_user_format }}"
        clean_install: true
      tags: gogs

    - name: create projects git repo for {{ user_gogs_name }} user
      uri:
        url: http://{{ gogs_hostname }}/api/v1/user/repos
        method: POST
        body: '{"name": "projects", "private": false}'
        body_format: json
        user: "{{ user_gogs_name }}"
        password: "{{ user_gogs_password }}"
        status_code: 200,201
        force_basic_auth: true
        ignore_errors: true
      tags: gogs

    - name: create projects git repo for generated users
      uri:
        url: http://{{ gogs_hostname }}/api/v1/user/repos
        method: POST
        body: '{"name": "projects", "private": false}'
        body_format: json
        user: "{{ item }}"
        password: "{{ user_gogs_password }}"
        status_code: 200,201
        force_basic_auth: true
        ignore_errors: true
      with_sequence: start=0 end={{ generated_gogs_user_count }} format="{{ generated_gogs_user_format }}"
      when: generate_gogs_users > 0
      tags: gogs

    - name: create temporary git directory
      tempfile:
        state: directory
        prefix: devops-oab-git
      register: git_dir
      tags: gogs

    - name: unarchive labs source archive
      unarchive:
        remote_src: yes
        src: "https://github.com/openshift-labs/devops-oab-labs/archive/{{ labs_github_ref }}.zip"
        dest: "{{ git_dir.path }}"
      tags: gogs

    - name: init projects git repo
      shell: |
        mv {{ git_dir.path }}/devops-oab-labs-{{ labs_github_ref }}/* {{ git_dir.path }}
        rm -rf {{ git_dir.path }}/devops-oab-labs-{{ labs_github_ref }}
        echo "solutions/" >> {{ git_dir.path }}/.gitignore
        git init
        git add . --all
        git config user.email "rhdeveloper@labs.com"
        git config user.name "rhdeveloper"
        git commit -m "Initial add"
      args:
        chdir: "{{ git_dir.path }}"
      tags: gogs

    - name: push projects git repo to Gogs for {{ user_gogs_name }} user
      shell: |
        git push -f http://{{ user_gogs_name }}:{{ user_gogs_password }}@{{ gogs_hostname }}/{{ user_gogs_name }}/projects.git master
      args:
        chdir: "{{ git_dir.path }}"
      tags: gogs

    - name: push projects git repo to Gogs for generated users
      shell: |
        git push -f http://{{ item }}:{{ user_gogs_password }}@{{ gogs_hostname }}/{{ item }}/projects.git master
      args:
        chdir: "{{ git_dir.path }}"
      with_sequence: start=0 end={{ generated_gogs_user_count }} format="{{ generated_gogs_user_format }}"
      when: generated_gogs_user_count > 0
      tags: gogs