- src: siamaksade.openshift_common_facts
  name: openshift_common_facts

- src: siamaksade.openshift_sonatype_nexus
  name: openshift_sonatype_nexus

- src: siamaksade.openshift_gogs
  name: openshift_gogs

- src: siamaksade.openshift_workshopper
  name: openshift_workshopper